#!/bin/ash


cat > "$HOME/.config/user-dirs.dirs" <<-EOF

XDG_DESKTOP_DIR="$HOME/PERSISTENT/Desktop"
XDG_DOWNLOAD_DIR="$HOME/PERSISTENT/Downloads"
XDG_TEMPLATES_DIR="$HOME/PERSISTENT/Templates"
XDG_PUBLICSHARE_DIR="$HOME/PERSISTENT/Public"
XDG_DOCUMENTS_DIR="$HOME/PERSISTENT/Documents"
XDG_MUSIC_DIR="$HOME/PERSISTENT/Music"
XDG_PICTURES_DIR="$HOME/PERSISTENT/Pictures"
XDG_VIDEOS_DIR="$HOME/PERSISTENT/Videos"
EOF
