#!/bin/ash

# VNC
iptables -A INPUT -i br0 -p tcp -s 10.4.9.73 --dport 5900:5999 -j ACCEPT
iptables -A INPUT -i br0 -p tcp --dport 5900:5999 -j REJECT

# KVM
iptables -A INPUT -i br0 -p tcp -s 132.230.4.0/24 --dport 16509 -j ACCEPT
iptables -A INPUT -i br0 -p tcp --dport 16509 -j REJECT

